### ISSUE TITLE
TypeError: 'vim.Task' object is not callable

### ISSUE THREAD

**Issue by abhinav-chittora** [rreubenur/vmware-pyvmomi-examples#8]
I have been trying to use create_and_remove_snapshot.py and when I create the snapshot, it is giving me error.

> Traceback (most recent call last):
>   File "final.py", line 252, in <module>
>     main()
>   File "final.py", line 210, in main
>     create_menu(content)
>   File "final.py", line 154, in create_menu
>     invoke_and_track(vm.CreateSnapshot(snapshot_name, description, dumpMemory, quiesce))
>   File "final.py", line 94, in invoke_and_track
>     wait_for_task(func (_args, *_kw))
> TypeError: 'vim.Task' object is not callable

This is the function call for invoke_and_track:- 
`invoke_and_track(vm.CreateSnapshot(snapshot_name, description, dumpMemory, quiesce))`

and definition of invoke_and_track is as follow:- 

> def invoke_and_track(func, _args, *_kw):
>     try :
>         task = func(_args, *_kw)
>         wait_for_task(func (_args, *_kw))
>     except:
>         raise

**Comment by vijayaraghavan31** [comment]
Im also getting the same issue, any solution for this?
